### ISSUE TITLE
error message of validation  

### ISSUE THREAD

**Issue by wfw9sr** [pdmfc/nova-inline-text#10]
It always return Error: Request failed with status code 422 to the user. 
Would it be possible to return the validation error message ?
![image](https://user-images.githubusercontent.com/6407134/99922900-e0bb7980-2d6d-11eb-9d35-8faf470353b3.png)

![image](https://user-images.githubusercontent.com/6407134/99922930-fd57b180-2d6d-11eb-8e0d-c2a3e94e6486.png)

**Comment by bernhardh** [comment]
Just to make sure - have you read also #8. Validation isn't working as it should at all.

**Comment by skoyah** [comment]
Working on a new major version to fix this problem.
For now, I've added the caveat to the docs 806b3c6.
