### ISSUE TITLE
Add support for Nova v4.6

### ISSUE THREAD

**Issue by xcalabuig** [pdmfc/nova-inline-text#12]
Add support for Laravel Nova 4.
Actually the fields dissappears and remain blank

**Comment by TMBL-DEV** [comment]
> Add support for Laravel Nova 4. Actually the fields dissappears and remain blank

is there any status on this update? 
Like is it going to be implemented? 
Is someone already making it?

Or no updates and we just have to wait and see?

**Comment by xcalabuig** [comment]
> 

no updates... try this.
https://github.com/outl1ne/nova-inline-text-field
