### ISSUE TITLE
Relationship Integration

### ISSUE THREAD

**Issue by tushar-kharmate** [pdmfc/nova-inline-text#5]
Your package is nicely working for inline edit for the Resource fields. 
It will be great if the same package will work for pivot fields.

Issue- Actually when I use InlineText on the pivot field it gives a success message('Value updated') on updating the value. But when I refreshed the page and cross-checked in the database, I found that the value is not updated in DB.

Thanks!

![Screenshot 2020-06-04 at 7 59 40 PM](https://user-images.githubusercontent.com/58930178/83770304-884cce80-a69e-11ea-9dbf-ed0ad8a294fb.png)

**Comment by skoyah** [comment]
Hi @tushar-kharmate thanks for the feedback!

Could you elaborate a little bit more on the issue?

Are you trying to use this package for a relationship?

**Comment by tushar-kharmate** [comment]
Hey @skoyah, Yes I'm trying to use it for BelongsToMany relationship.

I have two resources.
1. ProductGroup
2. Nutrients.

Pivot table for the above two resources - 'product_group_nutrients' with the following columns. ('id', 'product_group_id', 'nutrient_id', 'value').

I have implemented BelongsToMany relationship on both the side. 
In this, I'm trying to do Inline edit for extra field 'value' from the pivot table. By using InlineText from your package.

Here is my code snippet,
ProductGroup.php

`BelongsToMany::make('Nutrients')
                ->fields(function () {
                    return [
                        InlineText::make('Value (In Percentage)','value')->inlineOnIndex(),
                    ];
                }),`


Nutrient.php

`BelongsToMany::make('Product Groups','productGroups')
                ->fields(function () {
                    return [
                        InlineText::make('Value','value')->inlineOnIndex(),
                    ];
                }),`

You can see the screenshot in earlier post. 

Thanks!

**Comment by skoyah** [comment]
Thanks for the explanation @tushar-kharmate !

It makes sense your use case. I'll try to tackle this issue when I have some spare time. Fell free to PR's are also welcomed! :)

**Comment by tushar-kharmate** [comment]
Thanks, @skoyah, 
Yes I'll be happy to contribute. As I'm new to Laravel Nova, I'm learning nova.

**Comment by villeneuve-michael** [comment]
Hello,

I was just wondering if there is any status update on that enhancement? Maybe I could chip in? Let me know if I can help with this PR.

**Comment by skoyah** [comment]
Hi@villeneuve-michael ! I have been really busy lately with a lot of work to do! Would be nice if you could contribute to the package!

**Comment by villeneuve-michael** [comment]
Ok! I'll try to give it a shot. I'll try to make some time in the next week !
