### ISSUE TITLE
Update field triggers 422 validation error

### ISSUE THREAD

**Issue by xoco70** [pdmfc/nova-inline-text#7]
Hi, 

I'm trying to use your plugin, but I get this error message; 422.

```
{message: "The given data was invalid.",…}
errors: {operation: ["The operation field is required."], producer: ["The producer field is required."],…}
consumer: ["The consumer field is required."]
operation: ["The operation field is required."]
producer: ["The producer field is required."]
message: "The given data was invalid."
```

Here is the definition of my resource:

```
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            BelongsTo::make('Opération', 'operation', 'App\Nova\Operation'),
            BelongsTo::make('Producteur', 'producer', 'App\Nova\User'),
            BelongsTo::make('Consommateur', 'consumer', 'App\Nova\User'),
            Date::make('Début', 'date_ini')->required()->firstDayOfWeek(1),
            Date::make('Fin', 'date_end')->required()->firstDayOfWeek(1),
            InlineText::make('Prix de vente du kWh ( unité )', 'kwh_price')
                ->inlineOnIndex(function (NovaRequest $request) {
                    return $request->user()->isSuperAdmin();
                })->required(),
//            Currency::make('Prix de vente du kWh ( unité )', 'kwh_price')->required(),
        ];
    }
```

**Comment by skoyah** [comment]
Hi there @xoco70 . Did you try to use the validation rule `sometimes` on your other fields? When you're updating the inline field, all the other fields are being sent in the request. Thats why you have that error.

**Comment by xoco70** [comment]
let me try !

**Comment by skoyah** [comment]
If that does not work you can try to use ```->updateRules('sometimes'),``` instead of ```rules()```

**Comment by xoco70** [comment]
worked with `->sometimes()`. Thanks !

**Comment by skoyah** [comment]
I'll make sure I'll add this caveat to the docs. Thanks for pointing it out @xoco70 !

#8

**Comment by bernhardh** [comment]
I think an elegant way for this, where you don't lose validation on form view would be defining the index fields separatly with [Dynamic Field Methods](https://nova.laravel.com/docs/3.0/resources/fields.html#dynamic-field-methods). So just define the fields you want to show on index in the `fieldsForIndex` method, without any "form only" methods, like `rules`, `help`, etc.
